services:
- type: web
  name: linebot-flask-sander
  env: python
  repo: https://github.com/yzu1062016/line_bot.git
  plan: free
  autoDeploy: false
  buildCommand: pip install gunicorn -r requirements.txt
  startCommand: gunicorn app:app